### ISSUE TITLE
Hiccups in update to 2.22.1

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan2#686]
There are some hiccups even before the new stuff (tbb + base model).

JSON files were removed and moved to CmdStan, so our use of json stream don't work anymore.
This was for metric file. I'm not sure anymore if Stan still reads metric file or does it take in array?

Stan `var_context` functions are now virtual, which means that this does not work anymore. Not sure how should we handle these.

```
py_var_context(
        std::map<std::string,
          std::pair<std::vector<double>, std::vector<size_t> > >& vars_r,
        std::map<std::string,
          std::pair<std::vector<int>, std::vector<size_t> > >& vars_i)
      {
          vars_r_ = vars_r;
          vars_i_ = vars_i;
      }
```

```stan_fit.hpp:1526:34: error: cannot declare variable 'par_context' to be of abstract type 'pystan::io::py_var_context'
       pystan::io::py_var_context par_context(vars_r, vars_i);
``` 

Error msg here:

```
In file included from C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:681:0:
c:\users\user\github\pystan\pystan/stan_fit.hpp:843:89: error: invalid new-expression of abstract class type 'pystan::io::py_var_context'
         init_context_ptr.reset(new io::py_var_context(args.init_vars_r, args.init_vars_i));
                                                                                         ^
In file included from C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:680:0:
c:\users\user\github\pystan\pystan/py_var_context.hpp:32:11: note:   because the following virtual functions are pure within 'pystan::io::py_var_context':
     class py_var_context : public stan::io::var_context {
           ^
In file included from C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:679:0:
c:\users\user\github\pystan\pystan\stan\src/stan/io/var_context.hpp:124:16: note:      virtual void stan::io::var_context::validate_dims(const string&, const string&, const string&, const std::vector<long long unsigned int>&) const
   virtual void validate_dims(
                ^
In file included from C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:681:0:
c:\users\user\github\pystan\pystan/stan_fit.hpp: In instantiation of 'class pystan::stan_fit<anon_model_b01c1e46a9ce74a7d6b098bcad019062_namespace::anon_model_b01c1e46a9ce74a7d6b098bcad019062, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >':
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:9247:226:   required from here
c:\users\user\github\pystan\pystan/stan_fit.hpp:1430:32: error: cannot declare field 'pystan::stan_fit<anon_model_b01c1e46a9ce74a7d6b098bcad019062_namespace::anon_model_b01c1e46a9ce74a7d6b098bcad019062, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> > >::data_' to be of abstract type 'pystan::io::py_var_context'
     pystan::io::py_var_context data_;
                                ^
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp: In function 'PyObject* __pyx_pf_71stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202_2_call_sampler(PyObject*, PyObject*, PyObject*, PyObject*)':
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:9379:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_12 = ((__pyx_t_9 != __pyx_v_fitptr->param_names_oi().size()) != 0);
                              ^
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp: In function 'PyTypeObject* __Pyx_ImportType(PyObject*, const char*, const char*, size_t, __Pyx_ImportType_CheckSize)':
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:30195:53: warning: unknown conversion type character 'z' in format [-Wformat=]
             module_name, class_name, size, basicsize);
                                                     ^
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:30195:53: warning: unknown conversion type character 'z' in format [-Wformat=]
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:30195:53: warning: too many arguments for format [-Wformat-extra-args]
In file included from C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:681:0:
c:\users\user\github\pystan\pystan/stan_fit.hpp: In instantiation of 'std::vector<double> pystan::stan_fit<Model, RNG_t>::unconstrain_pars(vars_r_t&, vars_i_t&) [with Model = anon_model_b01c1e46a9ce74a7d6b098bcad019062_namespace::anon_model_b01c1e46a9ce74a7d6b098bcad019062; RNG_t = boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >; vars_r_t = std::map<std::__cxx11::basic_string<char>, std::pair<std::vector<double>, std::vector<long long unsigned int> > >; vars_i_t = std::map<std::__cxx11::basic_string<char>, std::pair<std::vector<int>, std::vector<long long unsigned int> > >]':
C:\Users\user\AppData\Local\Temp\pystan_wau1k_ag\stanfit4anon_model_b01c1e46a9ce74a7d6b098bcad019062_4928324538026200202.cpp:17455:87:   required from here
c:\users\user\github\pystan\pystan/stan_fit.hpp:1526:34: error: cannot declare variable 'par_context' to be of abstract type 'pystan::io::py_var_context'
       pystan::io::py_var_context par_context(vars_r, vars_i);
```

cc. @ariddell @mitzimorris

**Comment by ahartikainen** [comment]
There was a new virtual function which was not defined

**Comment by riddell-stan** [comment]
@ahartikainen FYI: I'm going to try to get httpstan working with 2.21 this week. Are you going to keep trying to get 2.21 working here?

**Comment by ahartikainen** [comment]
Yes, I have it working locally (multiprocessing doesn't work, but I think TBB should handle that: I just need to figure out all the env vars)
