### ISSUE TITLE
Segmentation fault (core dumped) at the end of sampling

### ISSUE THREAD

**Issue by anaosojnik** [stan-dev/pystan2#683]
#### Summary:
Segmentation fault (core dumped) error appears at the end of sampling, and Python script crashes.

#### Description:
I compile a stan model, and then sample from it using model.sampling() function. The sampler appears to be working fine (progress prints out on the console as it should), but it does not output a stanfit object. Before outputting this object, a segmentation fault appears and the python script crashes and closes. The same code was previously working in version 2.19.0.0. The error appears even when a new python virtual environment is set up on different computers.

I then tried downloading version 2.19.0.0 which worked previously but obtained an error. I also obtained the same error when trying to install 18.0.0-cvodes. A bunch of filed seem to be missing during compile (see part of the output below)

 x86_64-linux-gnu-gcc: error: pystan/stan/src/stan/lang/grammars/term_grammar_inst.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    x86_64-linux-gnu-gcc: error: pystan/stan/src/stan/lang/grammars/statement_2_grammar_inst.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    x86_64-linux-gnu-gcc: error: pystan/stan/src/stan/lang/grammars/whitespace_grammar_inst.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    x86_64-linux-gnu-gcc: error: pystan/stan/src/stan/lang/grammars/semantic_actions_def.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    In file included from pystan/_api.cpp:684:0:
    pystan/stanc.hpp:1:10: fatal error: stan/version.hpp: No such file or directory
     #include <stan/version.hpp>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.

#### Reproducible Steps:
I reinstalled stan, and ran previously working code with this new version.

#### Current Output:
No stanfit object output. Segmentation fault (core dumped)

#### Expected Output:
Stanfit object variable.

#### PyStan Version:
2.19.1.1

#### Python Version:
Python 3.6.9

#### Operating System:
Ubuntu 18.04.3 LTS

**Comment by ahartikainen** [comment]
Hi,

### Failure

That sounds weird. Are you able to compile different models? Did you recompile your model (no caching used?)

Is there possibility to share the code or maybe create some minimal working(failing) example. Maybe something has changed in Stan backend between 2.19.0 and 2.19.1

### CVODES

I think CVODES instructions has an error. It should really use the zip-file. 

    pip install https://github.com/stan-dev/pystan/archive/v2.18.0.0-cvodes.zip

But to get the latest (19.1.1) for cvodes you run do the following


    git clone --recursive https://github.com/stan-dev/pystan
    cd pystan
    git checkout cvodes
    python -m pip install .

**Comment by daeh** [comment]
I had this issue when the number passed via the `warmup` flag was equal to the number passed via the `iter` flag. (In my case at least, it would have been useful to pystan to catch the flags before sampling the model and producing a segfault.)

**Comment by rgerkin** [comment]
I can reproduce this issue. 

Pystan already doesn't allow n_warm > n_iter.  It should probably just disallow n_warm = n_iter until this is fixed, as I'm not sure what practical use case would require them to be equal.  I only encountered this in debugging when setting both to a low (and unfortunately equal) value in debugging a model.

**Comment by ahartikainen** [comment]
Yes, this is a bit of annoying thing in PyStan2 

    iter = warmup + samples

So user needs to do some mental arithmetic.

This is fixed in PyStan3 / CmdStanPy.

We could add additional checks.
